export const requiredDesignTokens = [
  'background',
  'foreground',
  'surface',
  'surface-subtle',
  'surface-elevated',
  'primary',
  'secondary',
  'border',
  'success',
  'warning',
  'danger',
  'info',
  'move-best',
  'move-blunder',
  'board-light',
  'board-dark',
  'radius-md',
  'shadow-md',
] as const;
